module.exports = {
  data: [
    {
      question: "Which command is used to display the running processes in Linux?",
      option1: "ps",
      option2: "proc",
      option3: "process",
      option4: "procinfo",
      ans: 1,
    },
    {
      question: "Which Linux file permission mode allows read, write, and execute for owner, and only read and execute for group and others?",
      option1: "chmod 711",
      option2: "chmod 755",
      option3: "chmod 644",
      option4: "chmod 777",
      ans: 2,
    },
    {
      question: "What command would you use to check disk usage in Linux?",
      option1: "du",
      option2: "df",
      option3: "disk",
      option4: "memory",
      ans: 2,
    },
    {
      question: "Which directory contains configuration files in Linux?",
      option1: "/bin",
      option2: "/root",
      option3: "/etc",
      option4: "/var",
      ans: 3,
    },
    {
      question: "What command is used to create a symbolic link in Linux?",
      option1: "ln -s",
      option2: "symlink",
      option3: "link -s",
      option4: "touch -l",
      ans: 1,
    },
    {
      question: "Which of the following is NOT a Linux shell?",
      option1: "Bash",
      option2: "Zsh",
      option3: "Fish",
      option4: "Command",
      ans: 4,
    },
    {
      question: "What command would you use to find text in files?",
      option1: "find",
      option2: "locate",
      option3: "grep",
      option4: "search",
      ans: 3,
    },
    {
      question: "Which command is used to display the current running processes with real-time updates?",
      option1: "ps -aux",
      option2: "processes",
      option3: "top",
      option4: "procview",
      ans: 3,
    },
    {
      question: "What signal is sent to a process when you press Ctrl+C in the terminal?",
      option1: "SIGTERM",
      option2: "SIGKILL",
      option3: "SIGINT",
      option4: "SIGSTOP",
      ans: 3,
    },
    {
      question: "Which of these directories typically contains system logs?",
      option1: "/var/log",
      option2: "/etc/log",
      option3: "/usr/log",
      option4: "/log",
      ans: 1,
    },
    {
      question: "Which of these is not a Python data type?",
      option1: "List",
      option2: "Dictionary",
      option3: "Array",
      option4: "Tuple",
      ans: 3,
    },
    {
      question: "What does the 'pip' command do in Python?",
      option1: "Executes Python code",
      option2: "Installs packages",
      option3: "Prints output",
      option4: "Tests scripts",
      ans: 2,
    },
    {
      question: "What will be the output of: len([1, 2, 3, 'a', 'b'])?",
      option1: "3",
      option2: "5",
      option3: "2",
      option4: "Error",
      ans: 2,
    },
    {
      question: "Which module is commonly used for HTTP requests in Python?",
      option1: "http",
      option2: "urllib",
      option3: "requests",
      option4: "fetch",
      ans: 3,
    },
    {
      question: "What is the correct way to create a virtual environment in Python?",
      option1: "venv myenv",
      option2: "python -m venv myenv",
      option3: "virtualenv create myenv",
      option4: "py venv myenv",
      ans: 2,
    },
    {
      question: "Which of these is used for string formatting in Python 3?",
      option1: "%s",
      option2: ".format()",
      option3: "f-strings",
      option4: "All of the above",
      ans: 4,
    },
    {
      question: "Which library is commonly used for data manipulation in Python?",
      option1: "Numpy",
      option2: "Pandas",
      option3: "Matplotlib",
      option4: "Scikit-learn",
      ans: 2,
    },
    {
      question: "What does the following code return: [x for x in range(5)]?",
      option1: "[0, 1, 2, 3, 4]",
      option2: "[1, 2, 3, 4, 5]",
      option3: "[0, 1, 2, 3, 4, 5]",
      option4: "Error",
      ans: 1,
    },
    {
      question: "What is the purpose of '__init__' in Python classes?",
      option1: "To initialize a new instance",
      option2: "To import modules",
      option3: "To define static methods",
      option4: "To iterate through objects",
      ans: 1,
    },
    {
      question: "Which of these is a correct way to open a file in Python?",
      option1: "file('example.txt', 'r')",
      option2: "open('example.txt', 'r')",
      option3: "read('example.txt')",
      option4: "fileopen('example.txt')",
      ans: 2,
    },
    {
      question: "Which AWS service is used for object storage?",
      option1: "EBS",
      option2: "S3",
      option3: "EFS",
      option4: "EC2",
      ans: 2,
    },
    {
      question: "What AWS service provides managed relational databases?",
      option1: "RDS",
      option2: "DynamoDB",
      option3: "DocumentDB",
      option4: "ElastiCache",
      ans: 1,
    },
    {
      question: "Which AWS service is used for serverless computing?",
      option1: "EC2",
      option2: "ECS",
      option3: "Lambda",
      option4: "Lightsail",
      ans: 3,
    },
    {
      question: "What is Amazon CloudFront?",
      option1: "Monitoring service",
      option2: "CDN service",
      option3: "Compute service",
      option4: "Database service",
      ans: 2,
    },
    {
      question: "Which service would you use to set up a virtual private cloud in AWS?",
      option1: "AWS Cloud",
      option2: "AWS VPN",
      option3: "AWS VPC",
      option4: "AWS Network",
      ans: 3,
    },
    {
      question: "What AWS service is used for container orchestration?",
      option1: "ECR",
      option2: "ECS",
      option3: "EKS",
      option4: "Both B and C",
      ans: 4,
    },
    {
      question: "Which service would you use for centralized logging in AWS?",
      option1: "CloudWatch",
      option2: "X-Ray",
      option3: "Inspector",
      option4: "CloudTrail",
      ans: 1,
    },
    {
      question: "What is AWS IAM primarily used for?",
      option1: "Storage management",
      option2: "Instance monitoring",
      option3: "Access management",
      option4: "Network configuration",
      ans: 3,
    },
    {
      question: "Which AWS service provides a managed Kubernetes service?",
      option1: "ECS",
      option2: "EC2",
      option3: "EKS",
      option4: "Fargate",
      ans: 3,
    },
    {
      question: "What AWS service would you use for load balancing?",
      option1: "ELB",
      option2: "ALB",
      option3: "NLB",
      option4: "All of the above",
      ans: 4,
    },
    {
      question: "Which file is used to define a Docker container?",
      option1: "Containerfile",
      option2: "Dockerfile",
      option3: "Compose file",
      option4: "Docker.config",
      ans: 2,
    },
    {
      question: "What command is used to list running Docker containers?",
      option1: "docker list",
      option2: "docker ps",
      option3: "docker show",
      option4: "docker containers",
      ans: 2,
    },
    {
      question: "What Docker command builds an image from a Dockerfile?",
      option1: "docker create",
      option2: "docker run",
      option3: "docker build",
      option4: "docker image",
      ans: 3,
    },
    {
      question: "Which of these is NOT a Docker object?",
      option1: "Images",
      option2: "Containers",
      option3: "Volumes",
      option4: "Scripts",
      ans: 4,
    },
    {
      question: "What is Docker Hub?",
      option1: "Management tool",
      option2: "Registry service",
      option3: "Orchestration tool",
      option4: "Monitoring tool",
      ans: 2,
    },
    {
      question: "Which command would you use to create a Docker network?",
      option1: "docker create network",
      option2: "docker network add",
      option3: "docker network create",
      option4: "docker add network",
      ans: 3,
    },
    {
      question: "What is the purpose of Docker Compose?",
      option1: "To build Docker images",
      option2: "To run multi-container applications",
      option3: "To manage Docker hosts",
      option4: "To monitor Docker performance",
      ans: 2,
    },
    {
      question: "What Docker command removes all stopped containers?",
      option1: "docker remove all",
      option2: "docker system prune",
      option3: "docker clean",
      option4: "docker container remove",
      ans: 2,
    },
    {
      question: "What is a Docker volume used for?",
      option1: "Network communication",
      option2: "Persistent data storage",
      option3: "Process isolation",
      option4: "Image versioning",
      ans: 2,
    },
    {
      question: "Which instruction in a Dockerfile specifies the base image?",
      option1: "FROM",
      option2: "BASE",
      option3: "IMAGE",
      option4: "IMPORT",
      ans: 1,
    },
    {
      question: "What is the smallest deployable unit in Kubernetes?",
      option1: "Container",
      option2: "Pod",
      option3: "Deployment",
      option4: "Service",
      ans: 2,
    },
    {
      question: "Which component runs on every node in Kubernetes?",
      option1: "etcd",
      option2: "kube-proxy",
      option3: "kube-scheduler",
      option4: "kube-apiserver",
      ans: 2,
    },
    {
      question: "What Kubernetes resource is used to manage stateful applications?",
      option1: "Deployment",
      option2: "StatefulSet",
      option3: "DaemonSet",
      option4: "ReplicaSet",
      ans: 2,
    },
    {
      question: "Which tool is commonly used for Kubernetes package management?",
      option1: "kubectl",
      option2: "kubeadm",
      option3: "Helm",
      option4: "Skaffold",
      ans: 3,
    },
    {
      question: "What is a Kubernetes Namespace used for?",
      option1: "Resource isolation",
      option2: "Storage management",
      option3: "Network routing",
      option4: "Load balancing",
      ans: 1,
    },
    {
      question: "Which command is used to view all pods in a Kubernetes cluster?",
      option1: "kubectl list pods",
      option2: "kubectl show pods",
      option3: "kubectl get pods",
      option4: "kubectl view pods",
      ans: 3,
    },
    {
      question: "What is a Kubernetes Ingress?",
      option1: "Storage driver",
      option2: "Database service",
      option3: "API routing",
      option4: "Network entry point",
      ans: 4,
    },
    {
      question: "What is the purpose of a Kubernetes ConfigMap?",
      option1: "Store configuration data",
      option2: "Monitor cluster health",
      option3: "Manage user access",
      option4: "Scale applications",
      ans: 1,
    },
    {
      question: "What component stores Kubernetes cluster state?",
      option1: "Controller Manager",
      option2: "Scheduler",
      option3: "etcd",
      option4: "kubelet",
      ans: 3,
    },
    {
      question: "Which of these is NOT a valid Kubernetes service type?",
      option1: "ClusterIP",
      option2: "NodePort",
      option3: "LoadBalancer",
      option4: "ExternalIP",
      ans: 4,
    },
  ],
};
