# Global settings
namespace: quiz-app
imageRegistry: "116981779461.dkr.ecr.us-east-1.amazonaws.com"

# Frontend configuration
frontend:
  name: frontend
  image:
    repository: frontend-js
    tag: 22004003
  replicas: 1
  service:
    port: 8080
    type: ClusterIP
  env:
    apiUrl: http://backend-api-service:3000/api/questions

# Backend configuration
backend:
  name: backend-api
  image:
    repository: backend-api
    tag: 22004003
  replicas: 1
  service:
    port: 3000
    type: ClusterIP

# Database configuration
database:
  name: mongodb
  image:
    repository: mongo
    tag: latest
  replicas: 1
  service:
    port: 27017
    type: ClusterIP
  storage:
    size: 5Gi

# MongoDB secret
mongoSecret:
  connectionString: bW9uZ29kYjovL21vbmdvZGItc2VydmljZToyNzAxNy9xdWl6LWFwcA==

# Ingress configuration
ingress:
  name: quiz-app-ingress
  class: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  rules:
    - host: quizapp.omar-domain.com
      paths:
        - path: /api/questions
          pathType: Prefix
          service: backend-api-service
          port: 3000
        - path: /
          pathType: Prefix
          service: frontend-service
          port: 8080